// main_website/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import { Providers } from "./provider";
import ClientThemeWrapper from "./ClientThemeWrapper";
import { CartProvider } from "@/components/context/CartContext";
import { TestOrderProvider } from "@/components/context/TestOrderContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "OurTopClinic",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning>
          <Providers>
            <CartProvider>
              <TestOrderProvider>
                <ClientThemeWrapper>
                  {children}
                </ClientThemeWrapper>
              </TestOrderProvider>
            </CartProvider>
          </Providers>
          <Toaster richColors position="top-center" />
        </body>
      </html>
    </ClerkProvider>
  );
}